-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: ../extensions/IPInfo/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE ipinfo_ip_changes (
  ipc_id BIGSERIAL NOT NULL,
  ipc_ip_hex TEXT NOT NULL,
  ipc_timestamp TIMESTAMPTZ NOT NULL,
  PRIMARY KEY(ipc_id)
);

CREATE INDEX ipc_timestamp ON ipinfo_ip_changes (ipc_timestamp);

CREATE INDEX ipc_ip_hex ON ipinfo_ip_changes (ipc_ip_hex);
