-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: ../extensions/IPInfo/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/ipinfo_ip_changes (
  ipc_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ipc_ip_hex BLOB NOT NULL, ipc_timestamp BLOB NOT NULL
);

CREATE INDEX ipc_timestamp ON /*_*/ipinfo_ip_changes (ipc_timestamp);

CREATE INDEX ipc_ip_hex ON /*_*/ipinfo_ip_changes (ipc_ip_hex);
