-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: ../extensions/IPInfo/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/ipinfo_ip_changes (
  ipc_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  ipc_ip_hex VARBINARY(35) NOT NULL,
  ipc_timestamp BINARY(14) NOT NULL,
  INDEX ipc_timestamp (ipc_timestamp),
  INDEX ipc_ip_hex (ipc_ip_hex),
  PRIMARY KEY(ipc_id)
) /*$wgDBTableOptions*/;
